sudo: required
dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

language: node_js
node_js:
  - "4"
  - "5"
  - "6"
  - "7"
  - "node"

before_install:
  - npm i npm@^4 -g
install:
  - npm install

script: npm run ci

