language: node_js
node_js:
  - "4"
  - "5"
  - "6"
  - "7"
  - "node"

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
sudo: required

script: npm run ci

